# Generated by Django 3.0.6 on 2020-05-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/canzoni/album/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_heading', models.CharField(max_length=250)),
                ('article_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/canzoni/artisti/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Artisti',
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.CreateModel(
            name='Scrittore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/libri/scrittori/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scrittori',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/libri/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generi', models.ManyToManyField(to='mdb_app.Genere')),
                ('scrittore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Scrittore')),
            ],
            options={
                'verbose_name_plural': 'Libri',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/film/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generi', models.ManyToManyField(to='mdb_app.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/canzoni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Artista')),
            ],
            options={
                'verbose_name_plural': 'Canzoni',
            },
        ),
        migrations.CreateModel(
            name='Attore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/film/attori/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('films', models.ManyToManyField(to='mdb_app.Film')),
            ],
            options={
                'verbose_name_plural': 'Attori',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Artista'),
        ),
    ]
