# Generated by Django 3.0.6 on 2020-05-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('copertina', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Arista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scrittore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('generi', models.ManyToManyField(to='mdb_app.Genere')),
                ('id_scrittore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Scrittore')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('pubblicazione', models.DateField()),
                ('generi', models.ManyToManyField(to='mdb_app.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('copertina', models.ImageField(upload_to='')),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Album')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Arista')),
            ],
        ),
        migrations.CreateModel(
            name='Attore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('foto', models.ImageField(upload_to='')),
                ('films', models.ManyToManyField(to='mdb_app.Film')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='id_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Arista'),
        ),
    ]
