# Generated by Django 3.0.6 on 2020-05-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0002_auto_20200512_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='id_artista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='canzone',
            old_name='id_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='canzone',
            old_name='id_artista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='id_scrittore',
            new_name='scrittore',
        ),
    ]
