# Generated by Django 3.0.6 on 2020-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0003_auto_20200518_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='titolo',
        ),
    ]
