# Generated by Django 3.0.6 on 2020-05-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0003_auto_20200512_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arista',
            new_name='Artista',
        ),
    ]
