# Generated by Django 3.0.6 on 2020-05-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0004_auto_20200512_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='copertina',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='attore',
            name='foto',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='canzone',
            name='copertina',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='scrittore',
            name='foto',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
    ]
