# Generated by Django 3.0.6 on 2020-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0004_auto_20200518_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
