# Generated by Django 3.0.6 on 2020-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0005_film_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='e_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
