# Generated by Django 3.0.6 on 2020-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0006_auto_20200517_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/canzoni/album/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/canzoni/artisti/'),
        ),
        migrations.AlterField(
            model_name='attore',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/film/attori/'),
        ),
        migrations.AlterField(
            model_name='canzone',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/canzoni'),
        ),
        migrations.AlterField(
            model_name='film',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/film/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/libri/'),
        ),
        migrations.AlterField(
            model_name='scrittore',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/libri/scrittori/'),
        ),
    ]
