# Generated by Django 3.0.6 on 2020-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0006_film_e_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
