# Generated by Django 3.0.6 on 2020-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0008_auto_20200521_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='e_src',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='gbooks_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
