# Generated by Django 3.0.6 on 2020-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0009_auto_20200523_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
