# Generated by Django 3.0.6 on 2020-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0011_auto_20200523_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attore',
            name='films',
            field=models.ManyToManyField(to='mdb_app.Film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='generi',
            field=models.ManyToManyField(to='mdb_app.Genere'),
        ),
    ]
