# Generated by Django 3.0.6 on 2020-05-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0014_auto_20200523_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canzone',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Artista'),
        ),
    ]
