# Generated by Django 3.0.6 on 2020-05-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0016_canzone_pubblicazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('src', models.ImageField(default='uploads/default.png', upload_to='uploads/%Y/%m/libri/autori/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Autori',
            },
        ),
        migrations.RemoveField(
            model_name='libro',
            name='scrittore',
        ),
        migrations.DeleteModel(
            name='Scrittore',
        ),
        migrations.AddField(
            model_name='libro',
            name='autore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb_app.Autore'),
        ),
    ]
