# Generated by Django 3.0.6 on 2020-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0017_auto_20200525_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='canzone',
            name='e_artista_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
