# Generated by Django 3.0.6 on 2020-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0018_canzone_e_artista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canzone',
            name='e_artista_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
